version: '3'
services:
  web:
    container_name: docker-node-mongo
    build: .
    ports:
      - 8080:8080
    links:
      - mongo
    restart: always
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    expose:
      - "27017"
    restart: always
